[features]
seeds = false
skip-lint = false
[programs.mainnet]
dutch_auction = "5FkPZLtYMt8PZ5r9yb3uTfCFJFb5NkfH9Nt3DXH5P2ha"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/noyan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
