-- AlterTable
ALTER TABLE "Auction" ALTER COLUMN "startingPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "minPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "boughtPrice" SET DATA TYPE DOUBLE PRECISION;
